import React, { useState, useCallback } from 'react';
import { Link } from 'react-router-dom';
import TeacherLayout from '../components/TeacherLayout';
import { STAAR_QUESTIONS, STAAR_REPORTING_CATEGORIES } from '../data/staar-questions';
import { getClassesByTeacher, getAssignments, getGrades, getGameResults } from '../utils/storage';
import { showAppToast } from '../utils/appToast';

/* ═══════════════════════════════════════════════════════════════
   PRINTABLES — Worksheets, Exit Tickets, Progress Reports
   Print-ready pages generated from TEKS question banks
   ═══════════════════════════════════════════════════════════════ */

const shuffle = a => { const b = [...a]; for (let i = b.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [b[i], b[j]] = [b[j], b[i]]; } return b; };

const TEKS_LABELS = {
  '3.2A': 'Place Value', '3.2B': 'Compare/Order Numbers', '3.2C': 'Number Line', '3.2D': 'Round Numbers',
  '3.3A': 'Represent Fractions', '3.3B': 'Fractions on NL', '3.3C': 'Part of Whole', '3.3D': 'Compare Fractions',
  '3.3E': 'Equivalent Fractions', '3.3F': 'Represent Equiv.', '3.3G': 'Explain Equiv.', '3.3H': 'Fractions > 1',
  '3.4A': 'Add & Subtract', '3.4B': 'Mental Math +/−', '3.4C': 'Multiply', '3.4D': 'Divide',
  '3.4E': 'Model ×/÷', '3.4F': 'Recall Facts', '3.4G': 'Arrays', '3.4H': 'Word Problem Sentences',
  '3.4I': 'Unknown in +/−', '3.4J': 'Unknown in ×/÷', '3.4K': 'Solve Problems',
  '3.5A': 'Patterns', '3.5B': 'Missing Number', '3.5C': 'Multiplication Patterns', '3.5D': 'Input/Output', '3.5E': 'Represent Relationships',
  '3.6A': 'Classify Shapes', '3.6B': 'Quadrilaterals', '3.6C': 'Area',
  '3.7A': 'Fractions from Zero', '3.7B': 'Perimeter', '3.7C': 'Elapsed Time', '3.7D': 'Units of Measure', '3.7E': 'Volume/Weight',
  '3.8A': 'Read Graphs', '3.8B': 'Interpret Data',
  '3.9A': 'Coins & Bills', '3.9B': 'Profit', '3.9C': 'Spending Plan', '3.9D': 'Saving & Borrowing', '3.9E': 'Charitable Giving',
};

const ALL_TEKS = Object.keys(TEKS_LABELS);

function openPrintWindow(html, title) {
  const win = window.open('', '_blank');
  if (!win) { showAppToast('Please allow popups to print.', { type: 'warning' }); return; }
  win.document.write(`<!DOCTYPE html><html><head><meta charset="utf-8"><title>${title}</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'Segoe UI', Arial, sans-serif; color: #1a1a1a; padding: 40px; font-size: 13px; line-height: 1.6; }
  h1 { font-size: 22px; margin-bottom: 4px; }
  h2 { font-size: 16px; margin: 20px 0 8px; border-bottom: 2px solid #ddd; padding-bottom: 4px; }
  .subtitle { color: #666; font-size: 12px; margin-bottom: 16px; }
  .question { margin: 14px 0; page-break-inside: avoid; }
  .question-num { font-weight: 700; }
  .choices { list-style: none; padding: 0; margin: 6px 0 0 16px; }
  .choices li { margin: 3px 0; }
  .choices li::before { content: '○ '; color: #999; }
  .answer-line { border-bottom: 1px solid #ccc; display: inline-block; width: 150px; height: 20px; margin-left: 8px; }
  .footer { margin-top: 30px; border-top: 1px solid #ddd; padding-top: 10px; font-size: 10px; color: #999; }
  .answer-key { margin-top: 30px; page-break-before: always; }
  .answer-key h2 { color: #2563eb; }
  .answer-key .answer-item { margin: 4px 0; font-size: 12px; }
  .student-info { display: flex; gap: 30px; margin-bottom: 16px; padding-bottom: 10px; border-bottom: 1px solid #eee; }
  .student-info div { flex: 1; }
  .student-info label { font-size: 10px; color: #999; text-transform: uppercase; letter-spacing: 1px; }
  .student-info .line { border-bottom: 1px solid #ccc; height: 24px; margin-top: 4px; }
  .progress-bar { height: 12px; background: #eee; border-radius: 6px; margin: 4px 0; }
  .progress-fill { height: 100%; border-radius: 6px; }
  .stat-grid { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 12px; margin: 12px 0; }
  .stat-box { border: 1px solid #ddd; border-radius: 8px; padding: 12px; text-align: center; }
  .stat-box .val { font-size: 24px; font-weight: 800; }
  .stat-box .lbl { font-size: 10px; color: #666; text-transform: uppercase; }
  @media print {
    body { padding: 20px; }
    button { display: none !important; }
  }
</style>
</head><body>${html}<script>setTimeout(()=>{window.print()},500)<\/script></body></html>`);
  win.document.close();
}

/* ── Generate worksheet ── */
function generateWorksheet(selectedTeks, count, includeKey) {
  let pool = STAAR_QUESTIONS.filter(q => selectedTeks.includes(q.teks) && q.type === 'mc');
  if (pool.length === 0) pool = STAAR_QUESTIONS.filter(q => q.type === 'mc');
  const questions = shuffle(pool).slice(0, count);
  const teksLabel = selectedTeks.length <= 3 ? selectedTeks.join(', ') : `${selectedTeks.length} standards`;

  let html = `<h1>Math Worksheet</h1>
<div class="subtitle">TEKS: ${teksLabel} • ${count} Questions • Generated by Quantegy AI</div>
<div class="student-info">
  <div><label>Name</label><div class="line"></div></div>
  <div><label>Date</label><div class="line"></div></div>
  <div><label>Period</label><div class="line"></div></div>
</div>`;

  questions.forEach((q, i) => {
    html += `<div class="question"><span class="question-num">${i + 1}.</span> ${q.q}`;
    if (q.choices) {
      html += `<ul class="choices">${q.choices.map(c => `<li>${c}</li>`).join('')}</ul>`;
    } else {
      html += `<br/>Answer: <span class="answer-line"></span>`;
    }
    html += `</div>`;
  });

  html += `<div class="footer">© Quantegy AI • TEKS-aligned worksheet • Grade 3 Mathematics</div>`;

  if (includeKey) {
    html += `<div class="answer-key"><h2>Answer Key</h2>`;
    questions.forEach((q, i) => {
      const ans = Array.isArray(q.answer) ? q.answer.join(', ') : q.answer;
      html += `<div class="answer-item"><strong>${i + 1}.</strong> ${ans} — <em>${q.explanation}</em></div>`;
    });
    html += `</div>`;
  }

  openPrintWindow(html, 'Math Worksheet');
}

/* ── Generate exit ticket ── */
function generateExitTicket(selectedTeks) {
  let pool = STAAR_QUESTIONS.filter(q => selectedTeks.includes(q.teks) && q.type === 'mc');
  if (pool.length === 0) pool = STAAR_QUESTIONS.filter(q => q.type === 'mc');
  const questions = shuffle(pool).slice(0, 3);
  const teksLabel = selectedTeks.join(', ');

  let html = `<h1>Exit Ticket</h1>
<div class="subtitle">TEKS: ${teksLabel} • 3 Questions</div>
<div class="student-info">
  <div><label>Name</label><div class="line"></div></div>
  <div><label>Date</label><div class="line"></div></div>
</div>`;

  questions.forEach((q, i) => {
    html += `<div class="question"><span class="question-num">${i + 1}.</span> ${q.q}`;
    if (q.choices) {
      html += `<ul class="choices">${q.choices.map(c => `<li>${c}</li>`).join('')}</ul>`;
    } else {
      html += `<br/>Answer: <span class="answer-line"></span>`;
    }
    html += `</div>`;
  });

  html += `<div style="margin-top:20px;border-top:1px solid #ddd;padding-top:12px">
    <strong style="font-size:11px">Self-Assessment:</strong>
    <div style="margin-top:6px;font-size:12px">
      ○ I fully understand &nbsp;&nbsp; ○ I mostly understand &nbsp;&nbsp; ○ I need more help
    </div>
  </div>`;

  html += `<div class="footer">© Quantegy AI • Exit Ticket</div>`;

  // Print 2 copies per page (2-up layout)
  const twoUp = `<div style="display:flex;gap:30px">${[1,2].map(() =>
    `<div style="flex:1;border:1px solid #ddd;padding:16px;border-radius:8px">${html}</div>`
  ).join('')}</div>`;

  openPrintWindow(twoUp, 'Exit Ticket');
}

/* ── Generate progress report ── */
function generateProgressReport(className, students, grades, assignments) {
  let html = `<h1>Student Progress Report</h1>
<div class="subtitle">${className} • Generated ${new Date().toLocaleDateString()}</div>`;

  if (!students || students.length === 0) {
    html += `<p>No students found in this class.</p>`;
    openPrintWindow(html, 'Progress Report');
    return;
  }

  students.forEach(student => {
    const name = typeof student === 'string' ? student : student.name || student.id || 'Unknown';
    const studentGrades = grades.filter(g => g.studentId === name);
    const totalScore = studentGrades.reduce((s, g) => s + (g.score || 0), 0);
    const avgScore = studentGrades.length > 0 ? Math.round(totalScore / studentGrades.length) : 0;
    const barColor = avgScore >= 80 ? '#22c55e' : avgScore >= 60 ? '#eab308' : '#ef4444';

    html += `<div style="page-break-inside:avoid;margin:20px 0;padding:16px;border:1px solid #ddd;border-radius:8px">
      <h2 style="border:none;margin:0 0 8px;font-size:16px">${name}</h2>
      <div class="stat-grid">
        <div class="stat-box"><div class="val" style="color:${barColor}">${avgScore}%</div><div class="lbl">Average</div></div>
        <div class="stat-box"><div class="val">${studentGrades.length}</div><div class="lbl">Assignments</div></div>
        <div class="stat-box"><div class="val">${studentGrades.filter(g => g.score >= 70).length}</div><div class="lbl">Passing</div></div>
      </div>
      <div class="progress-bar"><div class="progress-fill" style="width:${avgScore}%;background:${barColor}"></div></div>
      <div style="font-size:11px;color:#666;margin-top:8px">
        ${avgScore >= 80 ? 'Meeting expectations — keep up the great work!' :
          avgScore >= 60 ? 'Approaching expectations — targeted practice recommended.' :
          'Below expectations — intervention and additional support needed.'}
      </div>
    </div>`;
  });

  html += `<div class="footer">© Quantegy AI • Progress Report • Confidential</div>`;
  openPrintWindow(html, 'Progress Report');
}

/* ── Main Component ── */
export default function Printables() {
  const username = localStorage.getItem('quantegy-teacher-user');
  const [tab, setTab] = useState('worksheet');
  const [selectedTeks, setSelectedTeks] = useState(['3.4A', '3.4C']);
  const [questionCount, setQuestionCount] = useState(10);
  const [includeKey, setIncludeKey] = useState(true);
  const [selectedClass, setSelectedClass] = useState('');

  const classes = username ? getClassesByTeacher(username) : [];
  const assignments = getAssignments();
  const grades = getGrades();

  const toggleTeks = useCallback((teks) => {
    setSelectedTeks(prev => prev.includes(teks) ? prev.filter(t => t !== teks) : [...prev, teks]);
  }, []);

  const selectCategory = useCallback((catId) => {
    const cat = STAAR_REPORTING_CATEGORIES.find(c => c.id === catId);
    if (cat) setSelectedTeks(cat.teks);
  }, []);

  const handlePrintWorksheet = () => generateWorksheet(selectedTeks, questionCount, includeKey);
  const handlePrintExitTicket = () => generateExitTicket(selectedTeks);
  const handlePrintReport = () => {
    const cls = classes.find(c => c.id === selectedClass);
    if (!cls) { showAppToast('Please select a class.', { type: 'warning' }); return; }
    const classAssignments = assignments.filter(a => a.classId === cls.id);
    const classGrades = grades.filter(g => classAssignments.some(a => a.id === g.assignmentId));
    generateProgressReport(cls.name, cls.students || [], classGrades, classAssignments);
  };

  const tabs = [
    { id: 'worksheet', label: '📄 Worksheet', desc: 'TEKS-aligned practice sheets' },
    { id: 'exit', label: '🎯 Exit Ticket', desc: '3-question quick checks' },
    { id: 'report', label: '📊 Progress Report', desc: 'Per-student reports for parents' },
  ];

  return (
    <TeacherLayout>
      <div style={{ marginBottom: 24 }}>
        <h1 style={{ margin: '0 0 4px', fontSize: 24, color: '#0f172a' }}>🖨️ Printables</h1>
        <p style={{ margin: 0, color: '#64748b', fontSize: 14 }}>Generate print-ready worksheets, exit tickets, and progress reports.</p>
      </div>

      {/* Tabs */}
      <div style={{ display: 'flex', gap: 8, marginBottom: 24, flexWrap: 'wrap' }}>
        {tabs.map(t => (
          <button key={t.id} type="button" onClick={() => setTab(t.id)} style={{
            padding: '10px 18px', borderRadius: 10, border: tab === t.id ? '2px solid #2563eb' : '1px solid #e2e8f0',
            background: tab === t.id ? 'rgba(37,99,235,0.05)' : '#fff', cursor: 'pointer',
            fontSize: 13, fontWeight: tab === t.id ? 700 : 500, color: tab === t.id ? '#2563eb' : '#334155',
          }}>
            {t.label}
          </button>
        ))}
      </div>

      {/* Worksheet tab */}
      {tab === 'worksheet' && (
        <div style={{ maxWidth: 700 }}>
          <div style={cardStyle}>
            <h3 style={cardTitle}>Generate Worksheet</h3>
            <p style={{ fontSize: 13, color: '#64748b', marginBottom: 16 }}>
              Select TEKS standards and QBot will create a print-ready worksheet with answer key.
            </p>

            {/* Quick category selectors */}
            <div style={{ marginBottom: 16 }}>
              <div style={{ fontSize: 12, fontWeight: 700, color: '#0f172a', marginBottom: 8 }}>Quick Select by STAAR Category:</div>
              <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
                {STAAR_REPORTING_CATEGORIES.map((cat, i) => (
                  <button key={cat.id} type="button" onClick={() => selectCategory(cat.id)} style={{
                    padding: '6px 12px', borderRadius: 8, border: '1px solid #e2e8f0', background: '#f8fafc',
                    cursor: 'pointer', fontSize: 11, fontWeight: 600, color: '#334155',
                  }}>Cat {i + 1}: {cat.name.split(' ')[0]}</button>
                ))}
              </div>
            </div>

            {/* TEKS grid */}
            <div style={{ marginBottom: 16 }}>
              <div style={{ fontSize: 12, fontWeight: 700, color: '#0f172a', marginBottom: 8 }}>
                Select Standards ({selectedTeks.length} selected):
              </div>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6 }}>
                {ALL_TEKS.map(t => {
                  const sel = selectedTeks.includes(t);
                  const available = STAAR_QUESTIONS.some(q => q.teks === t);
                  return (
                    <button key={t} type="button" onClick={() => toggleTeks(t)} disabled={!available} style={{
                      padding: '4px 10px', borderRadius: 6, fontSize: 11, fontWeight: 600, cursor: available ? 'pointer' : 'default',
                      border: sel ? '2px solid #2563eb' : '1px solid #e2e8f0',
                      background: sel ? 'rgba(37,99,235,0.08)' : available ? '#fff' : '#f1f5f9',
                      color: sel ? '#2563eb' : available ? '#334155' : '#94a3b8',
                      opacity: available ? 1 : 0.5,
                    }}>
                      {t}
                    </button>
                  );
                })}
              </div>
            </div>

            {/* Options */}
            <div style={{ display: 'flex', gap: 20, alignItems: 'center', marginBottom: 20, flexWrap: 'wrap' }}>
              <div>
                <label style={labelStyle}>Questions</label>
                <select value={questionCount} onChange={e => setQuestionCount(Number(e.target.value))} style={selectStyle}>
                  {[5, 10, 15, 20, 25].map(n => <option key={n} value={n}>{n} questions</option>)}
                </select>
              </div>
              <div>
                <label style={{ ...labelStyle, display: 'flex', alignItems: 'center', gap: 6, cursor: 'pointer' }}>
                  <input type="checkbox" checked={includeKey} onChange={e => setIncludeKey(e.target.checked)} />
                  Include Answer Key
                </label>
              </div>
            </div>

            <button type="button" onClick={handlePrintWorksheet} disabled={selectedTeks.length === 0} style={{
              ...printBtn, opacity: selectedTeks.length === 0 ? 0.4 : 1,
            }}>
              🖨️ Generate & Print Worksheet
            </button>
          </div>
        </div>
      )}

      {/* Exit ticket tab */}
      {tab === 'exit' && (
        <div style={{ maxWidth: 700 }}>
          <div style={cardStyle}>
            <h3 style={cardTitle}>Generate Exit Ticket</h3>
            <p style={{ fontSize: 13, color: '#64748b', marginBottom: 16 }}>
              Quick 3-question check. Prints 2 tickets per page (cut in half). Includes student self-assessment.
            </p>

            <div style={{ marginBottom: 16 }}>
              <div style={{ fontSize: 12, fontWeight: 700, color: '#0f172a', marginBottom: 8 }}>Today's TEKS Focus:</div>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6 }}>
                {ALL_TEKS.map(t => {
                  const sel = selectedTeks.includes(t);
                  const available = STAAR_QUESTIONS.some(q => q.teks === t);
                  return (
                    <button key={t} type="button" onClick={() => toggleTeks(t)} disabled={!available} style={{
                      padding: '4px 10px', borderRadius: 6, fontSize: 11, fontWeight: 600, cursor: available ? 'pointer' : 'default',
                      border: sel ? '2px solid #7c3aed' : '1px solid #e2e8f0',
                      background: sel ? 'rgba(124,58,237,0.08)' : available ? '#fff' : '#f1f5f9',
                      color: sel ? '#7c3aed' : available ? '#334155' : '#94a3b8',
                      opacity: available ? 1 : 0.5,
                    }}>
                      {t}
                    </button>
                  );
                })}
              </div>
            </div>

            <button type="button" onClick={handlePrintExitTicket} disabled={selectedTeks.length === 0} style={{
              ...printBtn, background: '#7c3aed', opacity: selectedTeks.length === 0 ? 0.4 : 1,
            }}>
              🎯 Generate & Print Exit Ticket
            </button>
          </div>
        </div>
      )}

      {/* Progress report tab */}
      {tab === 'report' && (
        <div style={{ maxWidth: 700 }}>
          <div style={cardStyle}>
            <h3 style={cardTitle}>Generate Progress Report</h3>
            <p style={{ fontSize: 13, color: '#64748b', marginBottom: 16 }}>
              Print-ready student progress reports for parent conferences. Shows average scores, assignment completion, and recommendations.
            </p>

            {classes.length === 0 ? (
              <div style={{ padding: 20, textAlign: 'center', color: '#64748b' }}>
                <p>No classes found. <Link to="/teacher-class-new" style={{ color: '#2563eb' }}>Create a class</Link> first.</p>
              </div>
            ) : (
              <>
                <div style={{ marginBottom: 16 }}>
                  <label style={labelStyle}>Select Class</label>
                  <select value={selectedClass} onChange={e => setSelectedClass(e.target.value)} style={{ ...selectStyle, width: '100%' }}>
                    <option value="">-- Choose a class --</option>
                    {classes.map(c => (
                      <option key={c.id} value={c.id}>{c.name} ({c.students?.length || 0} students)</option>
                    ))}
                  </select>
                </div>

                <button type="button" onClick={handlePrintReport} disabled={!selectedClass} style={{
                  ...printBtn, background: '#059669', opacity: !selectedClass ? 0.4 : 1,
                }}>
                  📊 Generate & Print Reports
                </button>
              </>
            )}
          </div>
        </div>
      )}
    </TeacherLayout>
  );
}

const cardStyle = { background: '#fff', borderRadius: 14, padding: 24, border: '1px solid #e2e8f0', boxShadow: '0 1px 3px rgba(0,0,0,0.04)' };
const cardTitle = { margin: '0 0 4px', fontSize: 18, color: '#0f172a' };
const labelStyle = { fontSize: 12, fontWeight: 700, color: '#334155', display: 'block', marginBottom: 4 };
const selectStyle = { padding: '8px 12px', borderRadius: 8, border: '1px solid #e2e8f0', fontSize: 13, background: '#fff' };
const printBtn = { padding: '12px 24px', background: '#2563eb', color: '#fff', border: 'none', borderRadius: 10, cursor: 'pointer', fontSize: 14, fontWeight: 700 };
