import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { getClasses } from '../utils/storage';
import TeacherLayout from '../components/TeacherLayout';
import { TEKS_GRADES, getStandardsByGrade } from '../data/teks';
import { queryBank, addToBank, removeFromBank, getBankStats, loadBank, getBankedTeks } from '../data/testBank';
import ContentAdapter from '../components/ContentAdapter';
import CourseGenerator from '../components/CourseGenerator';
import RichTextEditor from '../components/RichTextEditor';
import { showAppToast } from '../utils/appToast';

/* ── Lightweight markdown → JSX renderer (no external deps) ── */
function renderMarkdown(text) {
  if (!text) return null;
  const lines = text.split('\n');
  const elements = [];
  let listItems = [];
  let listType = null; // 'ul' or 'ol'

  const flushList = () => {
    if (listItems.length === 0) return;
    const tag = listType === 'ol' ? 'ol' : 'ul';
    elements.push(React.createElement(tag, {
      key: `list-${elements.length}`,
      style: { margin: '6px 0 6px 8px', paddingLeft: 20, lineHeight: 1.7 },
    }, listItems.map((li, j) => React.createElement('li', { key: j }, inlineFormat(li)))));
    listItems = [];
    listType = null;
  };

  const inlineFormat = (str) => {
    const parts = [];
    const re = /(\*\*(.+?)\*\*)|(__(.+?)__)/g;
    let last = 0;
    let m;
    while ((m = re.exec(str)) !== null) {
      if (m.index > last) parts.push(str.slice(last, m.index));
      parts.push(React.createElement('strong', { key: `b${m.index}`, style: { color: '#0f172a' } }, m[2] || m[4]));
      last = re.lastIndex;
    }
    if (last < str.length) parts.push(str.slice(last));
    return parts.length ? parts : str;
  };

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const trimmed = line.trimStart();

    // Headings
    if (trimmed.startsWith('### ')) { flushList(); elements.push(<h4 key={i} style={{ margin: '18px 0 6px', fontSize: 15, fontWeight: 700, color: '#1e293b', borderBottom: 'none' }}>{inlineFormat(trimmed.slice(4))}</h4>); continue; }
    if (trimmed.startsWith('## ')) { flushList(); elements.push(<h3 key={i} style={{ margin: '20px 0 8px', fontSize: 17, fontWeight: 700, color: '#0f172a', borderBottom: '2px solid #e2e8f0', paddingBottom: 4 }}>{inlineFormat(trimmed.slice(3))}</h3>); continue; }
    if (trimmed.startsWith('# ')) { flushList(); elements.push(<h2 key={i} style={{ margin: '0 0 10px', fontSize: 20, fontWeight: 800, color: '#0f172a' }}>{inlineFormat(trimmed.slice(2))}</h2>); continue; }

    // Horizontal rule
    if (/^-{3,}$/.test(trimmed) || /^\*{3,}$/.test(trimmed)) { flushList(); elements.push(<hr key={i} style={{ border: 'none', borderTop: '1px solid #e2e8f0', margin: '12px 0' }} />); continue; }

    // Unordered list
    if (/^[-*•]\s+/.test(trimmed)) {
      if (listType !== 'ul') { flushList(); listType = 'ul'; }
      listItems.push(trimmed.replace(/^[-*•]\s+/, ''));
      continue;
    }
    // Ordered list
    const olMatch = trimmed.match(/^(\d+)[.)]\s+(.*)/);
    if (olMatch) {
      if (listType !== 'ol') { flushList(); listType = 'ol'; }
      listItems.push(olMatch[2]);
      continue;
    }

    flushList();

    // Blank line
    if (!trimmed) { elements.push(<div key={i} style={{ height: 8 }} />); continue; }

    // Normal paragraph
    elements.push(<p key={i} style={{ margin: '4px 0', lineHeight: 1.7, fontSize: 14, color: '#334155' }}>{inlineFormat(trimmed)}</p>);
  }
  flushList();
  return elements;
}

/* ── tiny helpers for export ── */
const buildPdfHtml = (title, questions, format) => {
  let body = `<h1 style="font-family:sans-serif">${title}</h1><p style="font-family:sans-serif;color:#555">Generated by Quantegy AI</p><hr/>`;
  questions.forEach((q, i) => {
    if (format === 'multiple-choice') {
      body += `<div style="margin:14px 0;font-family:sans-serif"><p><strong>${i + 1}. ${q.question}</strong></p><ul style="list-style:none;padding-left:8px">`;
      Object.entries(q.options || {}).forEach(([k, v]) => {
        const mark = k === q.correct ? ' ✓' : '';
        body += `<li style="margin:3px 0">${k}) ${v}${mark}</li>`;
      });
      body += `</ul>${q.misconception ? `<p style="font-size:12px;color:#888">Misconception: ${q.misconception}</p>` : ''}</div>`;
    } else if (format === 'true-false') {
      body += `<div style="margin:14px 0;font-family:sans-serif"><p><strong>${i + 1}. ${q.statement}</strong></p><p>Answer: <strong>${q.correct ? 'True' : 'False'}</strong></p>${q.explanation ? `<p style="font-size:12px;color:#888">${q.explanation}</p>` : ''}</div>`;
    } else {
      body += `<div style="margin:14px 0;font-family:sans-serif"><p><strong>${i + 1}. ${q.question}</strong></p><p>Answer: ${q.answer}</p>${q.misconception ? `<p style="font-size:12px;color:#888">Misconception: ${q.misconception}</p>` : ''}</div>`;
    }
  });
  return body;
};

const downloadFile = (blob, filename) => {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

const exportPdf = (title, questions, format) => {
  const html = buildPdfHtml(title, questions, format);
  const win = window.open('', '_blank');
  if (!win) { showAppToast('Please allow popups to export PDF.', { type: 'warning' }); return; }
  win.document.write(`<!DOCTYPE html><html><head><title>${title}</title></head><body>${html}<script>setTimeout(()=>{window.print()},400)<\/script></body></html>`);
  win.document.close();
};

const exportWord = (title, questions, format) => {
  const html = `<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns="http://www.w3.org/TR/REC-html40"><head><meta charset="utf-8"><title>${title}</title></head><body>${buildPdfHtml(title, questions, format)}</body></html>`;
  const blob = new Blob([html], { type: 'application/msword' });
  downloadFile(blob, `${title.replace(/[^a-z0-9]/gi, '_')}.doc`);
};

/* ── Source badge component ── */
const SourceBadge = ({ source }) => {
  const isBank = source === 'bank' || source === 'ai-saved';
  return (
    <span style={{
      display: 'inline-block', padding: '2px 8px', borderRadius: 4, fontSize: 10,
      fontWeight: 700, letterSpacing: 0.3,
      background: isBank ? '#dcfce7' : '#fef3c7',
      color: isBank ? '#166534' : '#92400e',
      border: `1px solid ${isBank ? '#86efac' : '#fcd34d'}`,
    }}>
      {isBank ? 'TEST BANK' : 'AI GENERATED'}
    </span>
  );
};

const TeacherCopilot = () => {
  const urlTab = typeof window !== 'undefined' ? new URLSearchParams(window.location.search).get('tab') : null;
  const [activeTab, setActiveTab] = useState(urlTab || 'planning');
  const [selectedClass, setSelectedClass] = useState('');
  const [gradeLevel, setGradeLevel] = useState('grade3');
  const [teksFilter, setTeksFilter] = useState('');
  const [prompt, setPrompt] = useState('');
  const [difficulty, setDifficulty] = useState('Developing');
  const [representation, setRepresentation] = useState('Mixed');
  const [questionFormat, setQuestionFormat] = useState('multiple-choice');
  const [numQuestions, setNumQuestions] = useState(5);
  const [feedbackType, setFeedbackType] = useState('Progress summary');
  const [studentResponse, setStudentResponse] = useState('');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [questions, setQuestions] = useState(null);
  const [questionsFormat, setQuestionsFormat] = useState('');
  const [bankCount, setBankCount] = useState(0);     // how many came from bank
  const [aiCount, setAiCount] = useState(0);          // how many from AI
  const [savedIds, setSavedIds] = useState(new Set()); // AI questions saved to bank
  const [shareLink, setShareLink] = useState('');
  const [error, setError] = useState(null);

  // Test Bank tab state
  const [bankStats, setBankStats] = useState(null);
  const [bankBrowse, setBankBrowse] = useState(null);
  const [bankTeksFilter, setBankTeksFilter] = useState('');
  const [bankFmtFilter, setBankFmtFilter] = useState('');

  const classes = getClasses();
  const standards = getStandardsByGrade(gradeLevel);

  const refreshBankStats = () => setBankStats(getBankStats());

  useEffect(() => { if (activeTab === 'testbank') refreshBankStats(); }, [activeTab]);

  /* ── Clear all AI-cached (ai-saved) questions from bank ── */
  const handleClearAiCache = () => {
    if (!window.confirm('This will remove all AI-generated questions from your test bank. Built-in seed questions will remain. Continue?')) return;
    const bank = loadBank();
    const seedOnly = bank.filter((q) => q.source === 'bank');
    // Clear localStorage extras — only seed remains
    localStorage.removeItem('allen-ace-test-bank');
    refreshBankStats();
    setBankBrowse(null);
  };

  /* ── Plain API call (for non-question endpoints) ── */
  const callApi = async (endpoint, body) => {
    setLoading(true);
    setError(null);
    setResult(null);
    setQuestions(null);
    setQuestionsFormat('');
    setShareLink('');
    setBankCount(0);
    setAiCount(0);
    setSavedIds(new Set());
    try {
      let res;
      try {
        res = await fetch(endpoint, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(body),
        });
      } catch (fetchErr) {
        throw new Error('Cannot reach the server. Make sure the backend is running on http://localhost:3001 and refresh the page.');
      }
      const text = await res.text();
      let data;
      try { data = text ? JSON.parse(text) : {}; } catch { throw new Error('Server returned invalid response. Is the backend running?'); }
      if (!data.success && data.error) throw new Error(data.error);
      if (!res.ok) throw new Error(data.error || `Request failed (${res.status})`);
      setResult(data.content);
      if (data.questions) { setQuestions(data.questions); setQuestionsFormat(data.format || 'multiple-choice'); }
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  /* ── Smart Question Generator: bank first, then AI ── */
  const handleGenerateQuestions = async () => {
    setLoading(true);
    setError(null);
    setResult(null);
    setQuestions(null);
    setQuestionsFormat('');
    setShareLink('');
    setBankCount(0);
    setAiCount(0);
    setSavedIds(new Set());

    try {
      // 1. Pull from test bank first
      const bankResults = queryBank({
        teks: teksFilter || undefined,
        grade: gradeLevel,
        format: questionFormat,
        difficulty: difficulty || undefined,
        representation: representation || undefined,
        limit: numQuestions,
      });

      const fromBank = bankResults.length;
      const need = numQuestions - fromBank;

      let allQuestions = bankResults.map((q) => ({ ...q, _source: q.source || 'bank' }));

      // 2. If bank doesn't have enough, call AI for the rest
      if (need > 0) {
        let res;
        try {
          res = await fetch('/api/generate-questions', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
              gradeLevel,
              teksStandard: teksFilter || null,
              difficulty,
              representation,
              questionFormat,
              numQuestions: need,
            }),
          });
        } catch (fetchErr) {
          throw new Error('Cannot reach the server. Make sure the backend is running on http://localhost:3001 and refresh the page.');
        }
        const text = await res.text();
        let data;
        try { data = text ? JSON.parse(text) : {}; } catch { throw new Error('Server returned invalid response. Is the backend running?'); }
        if (!data.success && data.error) throw new Error(data.error);

        if (data.questions && data.questions.length > 0) {
          const aiQs = data.questions.map((q, i) => ({
            ...q,
            id: q.id || `ai-${Date.now()}-${i}`,
            teks: teksFilter || '',
            grade: gradeLevel,
            format: questionFormat,
            difficulty,
            representation,
            _source: 'ai',
          }));
          allQuestions = [...allQuestions, ...aiQs];

          // ── Auto-cache: save AI questions to test bank automatically ──
          // This builds the bank over time and avoids regenerating the same questions
          const toCache = aiQs.map((q) => {
            const cached = { ...q, source: 'ai-saved', id: q.id };
            delete cached._source;
            return cached;
          });
          addToBank(toCache);
          toCache.forEach((q) => setSavedIds((prev) => new Set([...prev, q.id])));
        } else if (data.content) {
          // AI returned text but not structured – show as fallback
          setResult(data.content);
        }
      }

      setQuestions(allQuestions);
      setQuestionsFormat(questionFormat);
      setBankCount(fromBank);
      setAiCount(allQuestions.length - fromBank);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  const handleGeneratePlan = () => callApi('/api/generate-lesson-plan', {
    gradeLevel, teksStandard: teksFilter || null, prompt: prompt || 'Generate a comprehensive lesson plan aligned to TEKS.',
  });

  const handleGenerateFeedback = () => callApi('/api/generate-feedback', {
    gradeLevel, teksStandard: teksFilter || null, feedbackType,
  });

  const handleEvaluateResponse = () => {
    if (!studentResponse.replace(/<[^>]*>/g, '').trim()) { setError('Please enter a student response to evaluate.'); return; }
    callApi('/api/evaluate-response', {
      gradeLevel, teksStandard: teksFilter || null, studentResponse,
    });
  };

  const handleShareLink = async () => {
    if (!questions) return;
    try {
      const title = `${teksFilter || 'Math'} Questions – ${difficulty}`;
      const res = await fetch('/api/question-bank', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ title, questions, format: questionsFormat, gradeLevel, teksStandard: teksFilter, difficulty }),
      });
      const data = await res.json();
      if (data.success) {
        const link = `${window.location.origin}/quiz/${data.id}`;
        setShareLink(link);
      } else {
        showAppToast(data.error || 'Failed to create shareable link.', { type: 'error' });
      }
    } catch (err) {
      showAppToast(`Failed to create shareable link: ${err.message}`, { type: 'error' });
    }
  };

  /* ── Save an AI question to the bank ── */
  const handleSaveToBank = (q) => {
    const toSave = { ...q, source: 'ai-saved', id: q.id || `saved-${Date.now()}` };
    delete toSave._source;
    addToBank(toSave);
    setSavedIds((prev) => new Set([...prev, q.id]));
  };

  /* ── Save ALL AI questions to bank ── */
  const handleSaveAllAi = () => {
    if (!questions) return;
    const aiQs = questions.filter((q) => q._source === 'ai' && !savedIds.has(q.id));
    if (aiQs.length === 0) return;
    aiQs.forEach((q) => handleSaveToBank(q));
  };

  /* ── Test Bank browser ── */
  const handleBrowseBank = () => {
    const results = queryBank({
      teks: bankTeksFilter || undefined,
      format: bankFmtFilter || undefined,
    });
    setBankBrowse(results);
  };

  const handleDeleteFromBank = (id) => {
    removeFromBank(id);
    refreshBankStats();
    if (bankBrowse) setBankBrowse(bankBrowse.filter((q) => q.id !== id));
  };

  const tabs = [
    { id: 'course-gen', label: '\u2728 Full Course Generator' },
    { id: 'planning', label: 'Planning AI' },
    { id: 'questions', label: 'Question Generator' },
    { id: 'testbank', label: 'Test Bank' },
    { id: 'differentiate', label: 'Differentiate' },
    { id: 'feedback', label: 'Feedback Engine' },
    { id: 'rubric', label: 'Grading Assistant' },
    { id: 'translate', label: '\uD83C\uDF10 Translate & Adapt' },
  ];

  return (
    <TeacherLayout>
    <div>
      <div style={{ marginBottom: 24 }}>
        <h1 style={{ margin: 0, fontSize: 28 }}>AI Teacher Copilot</h1>
      </div>

      <div style={{ background: 'linear-gradient(135deg, #1e3a5f 0%, #0f172a 100%)', color: 'white', padding: 20, borderRadius: 12, marginBottom: 24 }}>
        <p style={{ margin: 0, fontSize: 14, opacity: 0.9 }}>Standards-aware • TEKS-aligned • Reduces workload</p>
        <p style={{ margin: '6px 0 0', fontSize: 15 }}>
          Generate lesson plans, questions, feedback, and grading support—all aligned to Texas standards.
        </p>
      </div>

      <div role="tablist" aria-label="AI Copilot tools" style={{ display: 'flex', gap: 8, marginBottom: 24, flexWrap: 'wrap' }}>
        {tabs.map((t) => (
          <button
            key={t.id}
            type="button"
            role="tab"
            aria-selected={activeTab === t.id}
            tabIndex={activeTab === t.id ? 0 : -1}
            onClick={() => { setActiveTab(t.id); setResult(null); setError(null); }}
            style={{
              padding: '10px 16px',
              border: activeTab === t.id ? '2px solid #007bff' : '1px solid #ddd',
              background: activeTab === t.id ? '#e8f4ff' : '#fff',
              borderRadius: 8,
              cursor: 'pointer',
              fontWeight: activeTab === t.id ? 600 : 400,
            }}
          >
            {t.label}
          </button>
        ))}
      </div>

      <div style={{ border: '1px solid #e2e8f0', borderRadius: 12, padding: 24, background: '#fff', minHeight: 320 }}>

        {/* ══════════ PLANNING AI ══════════ */}
        {activeTab === 'planning' && (
          <div>
            <h2 style={{ margin: '0 0 8px' }}>Standards-Aware Planning AI</h2>
            <p style={{ margin: '0 0 20px', color: '#64748b', fontSize: 14 }}>
              Lesson plans aligned to TEKS SE • Spiral review • Remediation pathways • Game suggestions by mastery gap
            </p>
            <div style={{ display: 'grid', gap: 12, marginBottom: 16 }}>
              <div>
                <label style={{ display: 'block', marginBottom: 4, fontWeight: 500 }}>Class</label>
                <select value={selectedClass} onChange={(e) => setSelectedClass(e.target.value)} style={{ padding: 8, width: '100%', maxWidth: 280 }}>
                  <option value="">Select class...</option>
                  {classes.map((c) => (<option key={c.id} value={c.id}>{c.name}</option>))}
                </select>
              </div>
              <div>
                <label style={{ display: 'block', marginBottom: 4, fontWeight: 500 }}>Grade / TEKS</label>
                <select value={gradeLevel} onChange={(e) => setGradeLevel(e.target.value)} style={{ padding: 8, width: '100%', maxWidth: 280 }}>
                  {TEKS_GRADES.map((g) => (<option key={g.id} value={g.id}>{g.label}</option>))}
                </select>
              </div>
              <div>
                <label style={{ display: 'block', marginBottom: 4, fontWeight: 500 }}>TEKS standard (optional)</label>
                <select value={teksFilter} onChange={(e) => setTeksFilter(e.target.value)} style={{ padding: 8, width: '100%', maxWidth: 400 }}>
                  <option value="">All standards</option>
                  {standards.map((s) => (<option key={s.id} value={s.id}>{s.id}: {s.description.slice(0, 50)}...</option>))}
                </select>
              </div>
              <div>
                <label style={{ display: 'block', marginBottom: 4, fontWeight: 500 }}>Request (e.g. "Lesson plan for 3.4C multiplication")</label>
                <input type="text" value={prompt} onChange={(e) => setPrompt(e.target.value)}
                  placeholder="Describe what you need..."
                  style={{ padding: 10, width: '100%', maxWidth: 400, boxSizing: 'border-box' }} />
              </div>
            </div>
            <button type="button" onClick={handleGeneratePlan} disabled={loading}
              style={{ padding: '10px 20px', background: loading ? '#94a3b8' : '#007bff', color: 'white', border: 'none', borderRadius: 8, cursor: loading ? 'wait' : 'pointer' }}>
              {loading ? 'Generating...' : 'Generate plan'}
            </button>
            {error && <p style={{ marginTop: 16, color: '#dc2626', fontSize: 14 }}>{error}</p>}
            {result && (
              <div style={{ marginTop: 24, padding: 20, background: '#f8fafc', borderRadius: 10, border: '1px solid #e2e8f0', maxHeight: 500, overflowY: 'auto' }}>
                {renderMarkdown(result)}
              </div>
            )}
          </div>
        )}

        {/* ══════════ QUESTION GENERATOR (bank-first) ══════════ */}
        {activeTab === 'questions' && (
          <div>
            <h2 style={{ margin: '0 0 8px' }}>Smart Question Generator</h2>
            <p style={{ margin: '0 0 20px', color: '#64748b', fontSize: 14 }}>
              Pulls from the Test Bank first (no AI tokens) • Fills the rest with AI • Save AI questions to grow your bank
            </p>
            <div style={{ display: 'grid', gap: 12, marginBottom: 16 }}>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
                <div>
                  <label style={{ display: 'block', marginBottom: 4, fontWeight: 500 }}>Grade / TEKS</label>
                  <select value={gradeLevel} onChange={(e) => setGradeLevel(e.target.value)} style={{ padding: 8, width: '100%' }}>
                    {TEKS_GRADES.map((g) => (<option key={g.id} value={g.id}>{g.label}</option>))}
                  </select>
                </div>
                <div>
                  <label style={{ display: 'block', marginBottom: 4, fontWeight: 500 }}>TEKS standard</label>
                  <select value={teksFilter} onChange={(e) => setTeksFilter(e.target.value)} style={{ padding: 8, width: '100%' }}>
                    <option value="">Select standard...</option>
                    {standards.map((s) => (<option key={s.id} value={s.id}>{s.id}: {s.description.slice(0, 50)}...</option>))}
                  </select>
                </div>
              </div>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 12 }}>
                <div>
                  <label style={{ display: 'block', marginBottom: 4, fontWeight: 500 }}>Question format</label>
                  <select value={questionFormat} onChange={(e) => setQuestionFormat(e.target.value)} style={{ padding: 8, width: '100%' }}>
                    <option value="multiple-choice">Multiple Choice (A-D)</option>
                    <option value="true-false">True / False</option>
                    <option value="open-ended">Open-Ended</option>
                  </select>
                </div>
                <div>
                  <label style={{ display: 'block', marginBottom: 4, fontWeight: 500 }}>Difficulty</label>
                  <select value={difficulty} onChange={(e) => setDifficulty(e.target.value)} style={{ padding: 8, width: '100%' }}>
                    <option>Emerging</option>
                    <option>Developing</option>
                    <option>Proficient</option>
                    <option>Mastered</option>
                  </select>
                </div>
                <div>
                  <label style={{ display: 'block', marginBottom: 4, fontWeight: 500 }}># of questions</label>
                  <select value={numQuestions} onChange={(e) => setNumQuestions(Number(e.target.value))} style={{ padding: 8, width: '100%' }}>
                    {[3, 5, 8, 10, 15, 20].map((n) => (<option key={n} value={n}>{n}</option>))}
                  </select>
                </div>
              </div>
              <div>
                <label style={{ display: 'block', marginBottom: 4, fontWeight: 500 }}>Representation type</label>
                <select value={representation} onChange={(e) => setRepresentation(e.target.value)} style={{ padding: 8, width: '100%', maxWidth: 280 }}>
                  <option>Visual / pictorial</option>
                  <option>Symbolic / equation</option>
                  <option>Word problem</option>
                  <option>Mixed</option>
                </select>
              </div>
            </div>
            <div style={{ display: 'flex', gap: 12, flexWrap: 'wrap', alignItems: 'center', marginBottom: 12 }}>
                <button type="button" onClick={handleGenerateQuestions} disabled={loading}
                style={{ padding: '10px 20px', background: loading ? '#94a3b8' : '#007bff', color: 'white', border: 'none', borderRadius: 8, cursor: loading ? 'wait' : 'pointer', fontSize: 14, fontWeight: 600 }}>
                {loading ? 'Generating...' : `Generate ${numQuestions} questions`}
              </button>
              <button type="button" onClick={async () => {
                setLoading(true); setError(null); setResult(null); setQuestions(null); setQuestionsFormat('');
                try {
                  const res = await fetch('/api/generate-questions-bloom', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({
                      gradeLevel, teksStandard: teksFilter || null,
                      bloomLevel: 'apply', numQuestions,
                    }),
                  });
                  const data = await res.json();
                  if (data.success && data.questions?.length) {
                    setQuestions(data.questions.map((q, i) => ({ ...q, id: q.id || `bloom-${i}`, _source: 'ai' })));
                    setQuestionsFormat(data.format || 'multiple-choice');
                    setAiCount(data.questions.length);
                    setBankCount(0);
                  } else if (data.success && data.content) setResult(data.content);
                  else setError(data.error || 'No questions generated');
                } catch (e) { setError(e.message); }
                finally { setLoading(false); }
              }} disabled={loading}
                style={{ padding: '10px 20px', background: loading ? '#94a3b8' : '#7c3aed', color: 'white', border: 'none', borderRadius: 8, cursor: loading ? 'wait' : 'pointer', fontSize: 14, fontWeight: 600 }}>
                {loading ? 'Generating...' : `Bloom's Taxonomy (Apply)`}
              </button>
            </div>

            {error && <p style={{ marginTop: 16, color: '#dc2626', fontSize: 14 }}>{error}</p>}

            {/* Source summary banner */}
            {questions && questions.length > 0 && (
              <div style={{
                marginTop: 16, padding: '10px 16px', borderRadius: 8, fontSize: 13,
                background: aiCount === 0 ? '#f0fdf4' : '#fefce8',
                border: `1px solid ${aiCount === 0 ? '#86efac' : '#fcd34d'}`,
                display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 8,
              }}>
                <span>
                  <strong>{bankCount}</strong> from Test Bank{aiCount > 0 && <> • <strong>{aiCount}</strong> from AI (auto-saved to bank)</>}
                  {aiCount === 0 && ' • No AI tokens used!'}
                </span>
              </div>
            )}

            {/* Structured question display */}
            {questions && questions.length > 0 && (
              <div style={{ marginTop: 16 }}>
                {/* Export & share toolbar */}
                <div style={{ display: 'flex', gap: 8, marginBottom: 16, flexWrap: 'wrap', alignItems: 'center' }}>
                  <button type="button"
                    onClick={() => exportPdf(`${teksFilter || 'Math'} Questions`, questions, questionsFormat)}
                    style={{ padding: '8px 14px', background: '#dc2626', color: '#fff', border: 'none', borderRadius: 6, cursor: 'pointer', fontSize: 13, fontWeight: 600 }}>
                    Export PDF
                  </button>
                  <button type="button"
                    onClick={() => exportWord(`${teksFilter || 'Math'} Questions`, questions, questionsFormat)}
                    style={{ padding: '8px 14px', background: '#2563eb', color: '#fff', border: 'none', borderRadius: 6, cursor: 'pointer', fontSize: 13, fontWeight: 600 }}>
                    Export Word
                  </button>
                  <button type="button"
                    onClick={handleShareLink}
                    style={{ padding: '8px 14px', background: '#059669', color: '#fff', border: 'none', borderRadius: 6, cursor: 'pointer', fontSize: 13, fontWeight: 600 }}>
                    Create Shareable Link
                  </button>
                  {shareLink && (
                    <div style={{ display: 'flex', alignItems: 'center', gap: 6, flex: 1, minWidth: 200 }}>
                      <input type="text" readOnly value={shareLink}
                        style={{ flex: 1, padding: 6, fontSize: 12, border: '1px solid #e2e8f0', borderRadius: 4, background: '#f0fdf4' }}
                        onClick={(e) => e.target.select()} />
                      <button type="button"
                        onClick={() => { navigator.clipboard.writeText(shareLink); }}
                        style={{ padding: '6px 10px', background: '#f0fdf4', border: '1px solid #059669', borderRadius: 4, cursor: 'pointer', fontSize: 11, fontWeight: 600, color: '#059669' }}>
                        Copy
                      </button>
                    </div>
                  )}
                </div>

                {/* Rendered questions */}
                <div style={{ display: 'grid', gap: 12 }}>
                  {questions.map((q, i) => (
                    <div key={q.id || i} style={{ padding: 16, background: '#f8fafc', border: '1px solid #e2e8f0', borderRadius: 10 }}>
                      {/* Source badge + save button */}
                      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 }}>
                        <SourceBadge source={q._source || q.source || 'ai'} />
                        {q._source === 'ai' && !savedIds.has(q.id) && (
                          <button type="button" onClick={() => handleSaveToBank(q)}
                            style={{
                              padding: '3px 10px', fontSize: 11, fontWeight: 600, borderRadius: 4,
                              background: '#f0fdf4', color: '#059669', border: '1px solid #059669', cursor: 'pointer',
                            }}>
                            + Save to bank
                          </button>
                        )}
                        {savedIds.has(q.id) && (
                          <span style={{ fontSize: 11, color: '#059669', fontWeight: 600 }}>Saved ✓</span>
                        )}
                      </div>

                      {questionsFormat === 'multiple-choice' && (
                        <>
                          <p style={{ margin: 0, fontWeight: 600, fontSize: 15 }}>{i + 1}. {q.question}</p>
                          <div style={{ marginTop: 8, display: 'grid', gap: 4 }}>
                            {Object.entries(q.options || {}).map(([k, v]) => (
                              <div key={k} style={{
                                padding: '6px 12px', borderRadius: 6, fontSize: 14,
                                background: k === q.correct ? '#dcfce7' : '#fff',
                                border: k === q.correct ? '1px solid #22c55e' : '1px solid #e5e7eb',
                                fontWeight: k === q.correct ? 600 : 400,
                              }}>
                                <strong>{k})</strong> {v} {k === q.correct && <span style={{ color: '#16a34a', marginLeft: 6 }}>✓</span>}
                              </div>
                            ))}
                          </div>
                          {q.misconception && <p style={{ margin: '8px 0 0', fontSize: 12, color: '#b45309', background: '#fefce8', padding: '4px 8px', borderRadius: 4 }}>Common misconception: {q.misconception}</p>}
                        </>
                      )}
                      {questionsFormat === 'true-false' && (
                        <>
                          <p style={{ margin: 0, fontWeight: 600, fontSize: 15 }}>{i + 1}. {q.statement}</p>
                          <p style={{ margin: '6px 0 0', fontSize: 14 }}>
                            Answer: <span style={{ fontWeight: 700, color: q.correct ? '#16a34a' : '#dc2626' }}>{q.correct ? 'True' : 'False'}</span>
                          </p>
                          {q.explanation && <p style={{ margin: '4px 0 0', fontSize: 12, color: '#64748b' }}>{q.explanation}</p>}
                        </>
                      )}
                      {questionsFormat === 'open-ended' && (
                        <>
                          <p style={{ margin: 0, fontWeight: 600, fontSize: 15 }}>{i + 1}. {q.question}</p>
                          <p style={{ margin: '6px 0 0', fontSize: 14 }}>Answer: {q.answer}</p>
                          {q.misconception && <p style={{ margin: '4px 0 0', fontSize: 12, color: '#b45309', background: '#fefce8', padding: '4px 8px', borderRadius: 4 }}>Common misconception: {q.misconception}</p>}
                        </>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Fallback: raw text if structured parse failed */}
            {result && !questions && (
              <div style={{ marginTop: 24, padding: 20, background: '#f8fafc', borderRadius: 10, border: '1px solid #e2e8f0', maxHeight: 500, overflowY: 'auto' }}>
                {renderMarkdown(result)}
              </div>
            )}
          </div>
        )}

        {/* ══════════ TEST BANK ══════════ */}
        {activeTab === 'testbank' && (
          <div>
            <h2 style={{ margin: '0 0 8px' }}>Test Bank</h2>
            <p style={{ margin: '0 0 20px', color: '#64748b', fontSize: 14 }}>
              Browse and manage your question library. Bank questions are served instantly—no AI tokens used.
            </p>

            {/* Stats cards */}
            {bankStats && (
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(140px, 1fr))', gap: 12, marginBottom: 20 }}>
                <div style={{ padding: 14, background: '#f0fdf4', border: '1px solid #86efac', borderRadius: 10, textAlign: 'center' }}>
                  <p style={{ margin: 0, fontSize: 28, fontWeight: 700, color: '#166534' }}>{bankStats.total}</p>
                  <p style={{ margin: '2px 0 0', fontSize: 12, color: '#475569' }}>Total Questions</p>
                </div>
                <div style={{ padding: 14, background: '#eff6ff', border: '1px solid #93c5fd', borderRadius: 10, textAlign: 'center' }}>
                  <p style={{ margin: 0, fontSize: 28, fontWeight: 700, color: '#1e40af' }}>{bankStats.teksCount}</p>
                  <p style={{ margin: '2px 0 0', fontSize: 12, color: '#475569' }}>TEKS Standards</p>
                </div>
                <div style={{ padding: 14, background: '#fefce8', border: '1px solid #fcd34d', borderRadius: 10, textAlign: 'center' }}>
                  <p style={{ margin: 0, fontSize: 28, fontWeight: 700, color: '#92400e' }}>{bankStats.seedCount}</p>
                  <p style={{ margin: '2px 0 0', fontSize: 12, color: '#475569' }}>Built-in</p>
                </div>
                <div style={{ padding: 14, background: '#fdf2f8', border: '1px solid #f9a8d4', borderRadius: 10, textAlign: 'center' }}>
                  <p style={{ margin: 0, fontSize: 28, fontWeight: 700, color: '#9d174d' }}>{bankStats.savedCount}</p>
                  <p style={{ margin: '2px 0 0', fontSize: 12, color: '#475569' }}>Teacher-Saved</p>
                </div>
              </div>
            )}

            {/* Auto-cache info + clear cache */}
            {bankStats && (
              <div style={{
                padding: '14px 16px', borderRadius: 10, marginBottom: 20,
                background: 'linear-gradient(135deg, #eff6ff, #f0fdf4)',
                border: '1px solid #93c5fd',
              }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: 10 }}>
                  <div>
                    <p style={{ margin: 0, fontSize: 14, fontWeight: 700, color: '#1e40af' }}>
                      Auto-Cache Enabled
                    </p>
                    <p style={{ margin: '4px 0 0', fontSize: 12, color: '#475569', lineHeight: 1.5 }}>
                      AI-generated questions are automatically saved to your test bank.
                      Next time the same TEKS/format is needed, cached questions are served instantly — no AI tokens used.
                      {bankStats.savedCount > 0 && (
                        <strong style={{ color: '#059669' }}>
                          {' '}You have {bankStats.savedCount} cached question{bankStats.savedCount !== 1 ? 's' : ''} saving you AI costs!
                        </strong>
                      )}
                    </p>
                  </div>
                  {bankStats.savedCount > 0 && (
                    <button type="button" onClick={handleClearAiCache}
                      style={{
                        padding: '6px 14px', fontSize: 12, fontWeight: 600, borderRadius: 6,
                        background: '#fee2e2', color: '#dc2626', border: '1px solid #fca5a5',
                        cursor: 'pointer', whiteSpace: 'nowrap', flexShrink: 0,
                      }}>
                      Clear AI Cache
                    </button>
                  )}
                </div>
              </div>
            )}

            {/* Coverage by TEKS */}
            {bankStats && (
              <div style={{ marginBottom: 20 }}>
                <h3 style={{ margin: '0 0 8px', fontSize: 15 }}>Coverage by TEKS</h3>
                <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
                  {getBankedTeks().map((t) => (
                    <span key={t.teks} style={{
                      padding: '4px 10px', borderRadius: 6, fontSize: 12, fontWeight: 600,
                      background: '#e8f0fe', color: '#1a5cba', border: '1px solid #c7d9f0',
                    }}>
                      {t.teks}: {t.count}q ({t.formats.join(', ')})
                    </span>
                  ))}
                </div>
              </div>
            )}

            {/* Browse / filter */}
            <div style={{ display: 'flex', gap: 10, marginBottom: 16, flexWrap: 'wrap', alignItems: 'flex-end' }}>
              <div>
                <label style={{ display: 'block', marginBottom: 4, fontWeight: 500, fontSize: 13 }}>Filter by TEKS</label>
                <select value={bankTeksFilter} onChange={(e) => setBankTeksFilter(e.target.value)} style={{ padding: 8 }}>
                  <option value="">All TEKS</option>
                  {(bankStats?.teksList || []).map((t) => (<option key={t} value={t}>{t}</option>))}
                </select>
              </div>
              <div>
                <label style={{ display: 'block', marginBottom: 4, fontWeight: 500, fontSize: 13 }}>Format</label>
                <select value={bankFmtFilter} onChange={(e) => setBankFmtFilter(e.target.value)} style={{ padding: 8 }}>
                  <option value="">All</option>
                  <option value="multiple-choice">Multiple Choice</option>
                  <option value="true-false">True / False</option>
                  <option value="open-ended">Open-Ended</option>
                </select>
              </div>
              <button type="button" onClick={handleBrowseBank}
                style={{ padding: '8px 16px', background: '#007bff', color: '#fff', border: 'none', borderRadius: 6, cursor: 'pointer', fontWeight: 600, fontSize: 13 }}>
                Browse
              </button>
            </div>

            {/* Browsed questions */}
            {bankBrowse && (
              <div>
                <p style={{ fontSize: 13, color: '#64748b', marginBottom: 10 }}>{bankBrowse.length} question{bankBrowse.length !== 1 ? 's' : ''} found</p>
                <div style={{ display: 'grid', gap: 10, maxHeight: 500, overflowY: 'auto' }}>
                  {bankBrowse.map((q) => (
                    <div key={q.id} style={{ padding: 14, background: '#fafafa', border: '1px solid #e2e8f0', borderRadius: 8 }}>
                      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 6 }}>
                        <div style={{ display: 'flex', gap: 6, alignItems: 'center', flexWrap: 'wrap' }}>
                          <span style={{ padding: '2px 8px', background: '#e8f0fe', color: '#1a5cba', borderRadius: 4, fontSize: 10, fontWeight: 700 }}>{q.teks}</span>
                          <span style={{ padding: '2px 8px', background: '#f1f5f9', color: '#475569', borderRadius: 4, fontSize: 10, fontWeight: 600 }}>{q.format}</span>
                          <span style={{ padding: '2px 8px', background: '#f1f5f9', color: '#475569', borderRadius: 4, fontSize: 10, fontWeight: 600 }}>{q.difficulty}</span>
                          <SourceBadge source={q.source} />
                        </div>
                        {q.source === 'ai-saved' && (
                          <button type="button" onClick={() => handleDeleteFromBank(q.id)}
                            style={{ padding: '3px 8px', fontSize: 11, background: '#fee2e2', color: '#dc2626', border: '1px solid #dc2626', borderRadius: 4, cursor: 'pointer' }}>
                            Delete
                          </button>
                        )}
                      </div>
                      <p style={{ margin: 0, fontSize: 14, fontWeight: 500 }}>
                        {q.question || q.statement || '(no preview)'}
                      </p>
                      {q.format === 'multiple-choice' && q.options && (
                        <div style={{ marginTop: 6, display: 'flex', gap: 8, flexWrap: 'wrap', fontSize: 12 }}>
                          {Object.entries(q.options).map(([k, v]) => (
                            <span key={k} style={{
                              padding: '2px 6px', borderRadius: 4,
                              background: k === q.correct ? '#dcfce7' : '#f8fafc',
                              border: k === q.correct ? '1px solid #22c55e' : '1px solid #e5e7eb',
                            }}>
                              {k}) {v}
                            </span>
                          ))}
                        </div>
                      )}
                      {q.format === 'true-false' && (
                        <p style={{ margin: '4px 0 0', fontSize: 12, color: '#64748b' }}>Answer: {q.correct ? 'True' : 'False'}</p>
                      )}
                      {q.format === 'open-ended' && q.answer && (
                        <p style={{ margin: '4px 0 0', fontSize: 12, color: '#64748b' }}>Answer: {q.answer.slice(0, 120)}{q.answer.length > 120 ? '...' : ''}</p>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        )}

        {/* ══════════ DIFFERENTIATE (Auto reading levels) ══════════ */}
        {activeTab === 'differentiate' && (
          <div>
            <h2 style={{ margin: '0 0 8px' }}>Auto-Differentiated Content</h2>
            <p style={{ margin: '0 0 20px', color: '#64748b', fontSize: 14 }}>
              Generate multiple reading-level versions of any prompt or instruction. Assign below/on/above grade level.
            </p>
            <div style={{ display: 'grid', gap: 12, marginBottom: 16 }}>
              <div>
                <label style={{ display: 'block', marginBottom: 4, fontWeight: 500 }}>Content to differentiate</label>
                <RichTextEditor value={studentResponse} onChange={setStudentResponse} placeholder="Paste a math problem, instruction, or prompt..." compact minHeight={60} />
              </div>
              <div>
                <label style={{ display: 'block', marginBottom: 4, fontWeight: 500 }}>Grade level</label>
                <select value={gradeLevel} onChange={(e) => setGradeLevel(e.target.value)} style={{ padding: 8, width: '100%', maxWidth: 200 }}>
                  {TEKS_GRADES.map((g) => (<option key={g.id} value={g.id}>{g.label}</option>))}
                </select>
              </div>
            </div>
            <button type="button" onClick={async () => {
              if (!studentResponse.replace(/<[^>]*>/g, '').trim()) { setError('Enter content to differentiate.'); return; }
              setLoading(true); setError(null); setResult(null);
              try {
                const res = await fetch('/api/generate-differentiated', {
                  method: 'POST',
                  headers: { 'Content-Type': 'application/json' },
                  body: JSON.stringify({ content: studentResponse, gradeLevel, levels: ['below', 'on', 'above'] }),
                });
                const data = await res.json();
                if (data.success && data.versions?.length) {
                  setResult(data.versions.map((v, i) => `**${v.level?.toUpperCase() || 'Level ' + (i + 1)}**\n\n${v.text}`).join('\n\n---\n\n'));
                } else if (data.success && data.content) setResult(data.content);
                else setError(data.error || 'No versions generated');
              } catch (e) { setError(e.message); }
              finally { setLoading(false); }
            }} disabled={loading || !studentResponse.replace(/<[^>]*>/g, '').trim()}
              style={{ padding: '10px 20px', background: loading ? '#94a3b8' : '#7c3aed', color: 'white', border: 'none', borderRadius: 8, cursor: loading ? 'wait' : 'pointer' }}>
              {loading ? 'Generating...' : 'Generate 3 Reading Levels'}
            </button>
            {error && <p style={{ marginTop: 16, color: '#dc2626', fontSize: 14 }}>{error}</p>}
            {result && (
              <div style={{ marginTop: 24, padding: 20, background: '#faf5ff', borderRadius: 10, border: '1px solid #e9d5ff', maxHeight: 500, overflowY: 'auto' }}>
                {renderMarkdown(result)}
              </div>
            )}
          </div>
        )}

        {/* ══════════ FEEDBACK ENGINE ══════════ */}
        {activeTab === 'feedback' && (
          <div>
            <h2 style={{ margin: '0 0 8px' }}>AI Feedback Engine</h2>
            <p style={{ margin: '0 0 20px', color: '#64748b', fontSize: 14 }}>
              Personalised student feedback • Misconception patterns • Intervention strategies • Parent communication drafts
            </p>
            <div style={{ display: 'grid', gap: 12, marginBottom: 16 }}>
              <div>
                <label style={{ display: 'block', marginBottom: 4, fontWeight: 500 }}>Grade / TEKS</label>
                <select value={gradeLevel} onChange={(e) => setGradeLevel(e.target.value)} style={{ padding: 8, width: '100%', maxWidth: 280 }}>
                  {TEKS_GRADES.map((g) => (<option key={g.id} value={g.id}>{g.label}</option>))}
                </select>
              </div>
              <div>
                <label style={{ display: 'block', marginBottom: 4, fontWeight: 500 }}>TEKS standard (optional)</label>
                <select value={teksFilter} onChange={(e) => setTeksFilter(e.target.value)} style={{ padding: 8, width: '100%', maxWidth: 400 }}>
                  <option value="">All standards</option>
                  {standards.map((s) => (<option key={s.id} value={s.id}>{s.id}: {s.description.slice(0, 50)}...</option>))}
                </select>
              </div>
              <div>
                <label style={{ display: 'block', marginBottom: 4, fontWeight: 500 }}>Feedback type</label>
                <select value={feedbackType} onChange={(e) => setFeedbackType(e.target.value)} style={{ padding: 8, width: '100%', maxWidth: 280 }}>
                  <option>Progress summary</option>
                  <option>Misconception breakdown</option>
                  <option>Intervention suggestions</option>
                  <option>Parent communication draft</option>
                </select>
              </div>
            </div>
            <button type="button" onClick={handleGenerateFeedback} disabled={loading}
              style={{ padding: '10px 20px', background: loading ? '#94a3b8' : '#007bff', color: 'white', border: 'none', borderRadius: 8, cursor: loading ? 'wait' : 'pointer' }}>
              {loading ? 'Generating...' : 'Generate feedback'}
            </button>
            {error && <p style={{ marginTop: 16, color: '#dc2626', fontSize: 14 }}>{error}</p>}
            {result && (
              <div style={{ marginTop: 24, padding: 20, background: '#f8fafc', borderRadius: 10, border: '1px solid #e2e8f0', maxHeight: 500, overflowY: 'auto' }}>
                {renderMarkdown(result)}
              </div>
            )}
          </div>
        )}

        {/* ══════════ GRADING ASSISTANT ══════════ */}
        {activeTab === 'rubric' && (
          <div>
            <h2 style={{ margin: '0 0 8px' }}>Rubric + Grading Assistant</h2>
            <p style={{ margin: '0 0 20px', color: '#64748b', fontSize: 14 }}>
              Evaluate written explanations • Suggest rubric scores • Flag patterns • Track reasoning quality over time
            </p>
            <div style={{ display: 'grid', gap: 12, marginBottom: 16 }}>
              <div>
                <label style={{ display: 'block', marginBottom: 4, fontWeight: 500 }}>Grade / TEKS</label>
                <select value={gradeLevel} onChange={(e) => setGradeLevel(e.target.value)} style={{ padding: 8, width: '100%', maxWidth: 280 }}>
                  {TEKS_GRADES.map((g) => (<option key={g.id} value={g.id}>{g.label}</option>))}
                </select>
              </div>
              <div>
                <label style={{ display: 'block', marginBottom: 4, fontWeight: 500 }}>TEKS / rubric criteria</label>
                <select value={teksFilter} onChange={(e) => setTeksFilter(e.target.value)} style={{ padding: 8, width: '100%', maxWidth: 400 }}>
                  <option value="">Select standard...</option>
                  {standards.map((s) => (<option key={s.id} value={s.id}>{s.id}: {s.description.slice(0, 50)}...</option>))}
                </select>
              </div>
              <div>
                <label style={{ display: 'block', marginBottom: 4, fontWeight: 500 }}>Student response to evaluate</label>
                <RichTextEditor value={studentResponse} onChange={setStudentResponse} placeholder="Paste student's written explanation or work here..." compact minHeight={60} />
              </div>
            </div>
            <button type="button" onClick={handleEvaluateResponse} disabled={loading}
              style={{ padding: '10px 20px', background: loading ? '#94a3b8' : '#007bff', color: 'white', border: 'none', borderRadius: 8, cursor: loading ? 'wait' : 'pointer' }}>
              {loading ? 'Evaluating...' : 'Evaluate & suggest score'}
            </button>
            {error && <p style={{ marginTop: 16, color: '#dc2626', fontSize: 14 }}>{error}</p>}
            {result && (
              <div style={{ marginTop: 24, padding: 20, background: '#f8fafc', borderRadius: 10, border: '1px solid #e2e8f0', maxHeight: 500, overflowY: 'auto' }}>
                {renderMarkdown(result)}
              </div>
            )}
          </div>
        )}
        {/* ══════════ FULL COURSE GENERATOR ══════════ */}
        {activeTab === 'course-gen' && <CourseGenerator teacher={localStorage.getItem('allen-ace-teacher-user') || 'teacher'} />}

        {/* ══════════ TRANSLATE & ADAPT ══════════ */}
        {activeTab === 'translate' && <ContentAdapter />}
      </div>
    </div>
    </TeacherLayout>
  );
};

export default TeacherCopilot;
